### ISSUE TITLE
Train on one dataset, predict on other?

### ISSUE THREAD

**Issue by ViriatoII** [JiaLiVUMC/scMRMA#1]
Hi,

Can I train the classifier on a dataset and apply it on another? I don't see how to do it, maybe with the "selfDB" parameter?

Kind regards,
Ricardo

**Comment by JiaLiVUMC** [comment]
Hi Ricardo,

No. The parameter "selfDB" means you can use modified existed databse or self-created hierarchical databases. But scMRMA is not able to do the training for hierarchical database. Maybe you can try Garnett.

Thanks,
Jia

**Comment by ViriatoII** [comment]
Thank you for the fast answer!
