### ISSUE TITLE
install the package

### ISSUE THREAD

**Issue by MWRR** [JiaLiVUMC/scMRMA#2]
I was trying to install scMRMA package as follow
`devtools::install_github("JiaLiVUMC/scMRMA")`
But I couldn't, I got this error

_Downloading GitHub repo _JiaLiVUMC/scMRMA@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
 cannot open URL _'https://api.github.com/repos/JiaLiVUMC/scMRMA/tarball/HEAD'_

**Comment by JiaLiVUMC** [comment]
Hi @MWRR,

I am sorry I have no idea on this issue. But I found several similar questions that may help. I put links below:

1. https://stackoverflow.com/questions/53845962/having-trouble-getting-devtoolsinstall-github-to-work-in-r-on-win-7-64bit-ma
2. https://github.com/facebookincubator/GeoLift/issues/53

Best
