### ISSUE TITLE
Error in scMRMA(input = brain) : Less than 200 genes

### ISSUE THREAD

**Issue by milenadoroszko** [JiaLiVUMC/scMRMA#3]
Hi,

thanks for developing such a promising package! 
I was trying to run it on my Seurat object (Seurat object of 63k cells, integrated over 4k genes) with default parameters and I'm getting this error

Error in scMRMA(input = brain) : Less than 200 genes

I'm getting a similar error when using selfDefinedDatabase. 

It seems to run OK on the example mouse dataset. Any ideas on how to solve it?

**Comment by JiaLiVUMC** [comment]
Thanks for using scMRMA. If your input is a Seurat object, scMRMA will extract count matrix firstly. 

The code is scdata <- Seurat::GetAssayData(input,slot="counts”). If the error ‘Less than 200 genes’, it means your count matrix is less than 200 rows. 

If your data is integrated, maybe try scMRMA before integration.

Best
